// js/examples.js — Example sentences keyed by English word/phrase
export const EXAMPLES = {

  // ── Verbs ─────────────────────────────────────────────────────────────
  "abandon":        "He had to abandon his car in the snow and walk home.",
  "accelerate":     "The car began to accelerate as it went downhill.",
  "accomplish":     "She managed to accomplish all her goals before the deadline.",
  "accuse":         "He was accused of taking money from the company.",
  "achieve":        "Hard work and dedication helped her achieve success.",
  "acquire":        "The company decided to acquire a smaller business.",
  "adapt":          "Animals must adapt to changes in their environment to survive.",
  "adjust":         "Please adjust the volume so everyone can hear clearly.",
  "adopt":          "The government adopted a new policy to reduce pollution.",
  "advertise":      "They advertised the new product on television and social media.",
  "affect":         "The heavy rain affected the outcome of the outdoor event.",
  "afford":         "I can't afford to buy a new computer right now.",
  "analyze":        "Scientists need to analyze the data before drawing conclusions.",
  "announce":       "The principal announced the new school rules at assembly.",
  "apply":          "You should apply for the scholarship before the deadline.",
  "appreciate":     "I really appreciate your help with the project.",
  "approach":       "We need to approach this problem in a different way.",
  "approve":        "The board approved the budget for next year.",
  "argue":          "They argued about the best way to solve the issue.",
  "arrange":        "She arranged the meeting for Monday morning.",
  "assist":         "Volunteers were asked to assist with the local festival.",
  "assume":         "Don't assume the answer is correct without checking first.",
  "attempt":        "He made several attempts to fix the broken machine.",
  "attract":        "The colorful flowers attracted many bees to the garden.",
  "avoid":          "Try to avoid eating too much sugar for better health.",
  "blame":          "Don't blame others for your own mistakes.",
  "calculate":      "Can you calculate how much money we need for the trip?",
  "capture":        "The photographer captured a beautiful sunset over the ocean.",
  "cause":          "Smoking can cause serious health problems over time.",
  "challenge":      "The new project challenged the team to think creatively.",
  "claim":          "He claimed he had never seen the document before.",
  "collaborate":    "The two companies decided to collaborate on the new product.",
  "communicate":    "It is important to communicate clearly in the workplace.",
  "compare":        "Let's compare the prices before making a decision.",
  "compete":        "Students from across the country came to compete in the contest.",
  "complain":       "Several customers complained about the long waiting time.",
  "complete":       "She completed the assignment an hour before the deadline.",
  "concentrate":    "I find it hard to concentrate when there is loud music.",
  "confirm":        "Please confirm your reservation by calling the hotel.",
  "connect":        "The new bridge will connect the two islands.",
  "consider":       "You should consider all the options before deciding.",
  "consume":        "Modern cities consume a huge amount of electricity every day.",
  "contribute":     "Everyone can contribute to protecting the environment.",
  "convince":       "He tried to convince his parents to let him study abroad.",
  "cope":           "It can be difficult to cope with stress during exam season.",
  "create":         "Art allows people to create and express their ideas freely.",
  "criticize":      "The reporter criticized the government's response to the disaster.",
  "damage":         "The storm damaged many buildings in the town.",
  "debate":         "The class debated whether social media is good or bad.",
  "decline":        "The number of wild birds has declined over the past decade.",
  "decrease":       "Sales decreased sharply during the economic slowdown.",
  "define":         "It is important to define the problem clearly before solving it.",
  "deliver":        "The package was delivered to the wrong address by mistake.",
  "demand":         "Customers are demanding better quality products at lower prices.",
  "demonstrate":    "The teacher demonstrated how to perform the experiment safely.",
  "depend":         "The result will depend on how much effort you put in.",
  "describe":       "Can you describe what the thief looked like?",
  "design":         "She designed a logo for the school festival.",
  "destroy":        "The fire destroyed several houses in the neighborhood.",
  "develop":        "The country has been working to develop its tourism industry.",
  "direct":         "The police officer directed traffic after the accident.",
  "discover":       "Scientists discovered a new species of fish in the deep ocean.",
  "discuss":        "Let's discuss the plan in more detail at tomorrow's meeting.",
  "distribute":     "Volunteers distributed food and supplies to the victims.",
  "divide":         "The class was divided into small groups for the activity.",
  "earn":           "She worked hard to earn enough money for college tuition.",
  "educate":        "It is the school's job to educate students about health and safety.",
  "eliminate":      "The new software helped eliminate most of the errors.",
  "emphasize":      "The teacher emphasized the importance of regular revision.",
  "encourage":      "My parents always encouraged me to pursue my dreams.",
  "ensure":         "Please ensure all windows are closed before you leave.",
  "establish":      "The organization was established to protect endangered animals.",
  "estimate":       "We estimate the project will take about three months to complete.",
  "evaluate":       "The committee will evaluate all applications next week.",
  "examine":        "The doctor examined the patient carefully.",
  "exhibit":        "The museum will exhibit rare paintings from the 17th century.",
  "expand":         "The company plans to expand its business into Asia.",
  "explain":        "Could you explain the rules of the game one more time?",
  "export":         "Japan exports a large number of cars every year.",
  "expose":         "The investigation exposed corruption within the organization.",
  "express":        "Music is a powerful way to express your feelings.",
  "extend":         "The government decided to extend the deadline by two weeks.",
  "focus":          "Try to focus on the most important tasks first.",
  "force":          "The storm forced hundreds of people to leave their homes.",
  "generate":       "Wind turbines generate electricity without producing pollution.",
  "guarantee":      "The company guarantees a full refund if you are not satisfied.",
  "handle":         "She is experienced at handling difficult situations at work.",
  "harm":           "Too much sunlight can harm your skin in the long run.",
  "identify":       "Researchers identified three main causes of the problem.",
  "ignore":         "You shouldn't ignore warning signs of illness.",
  "illustrate":     "The chart illustrates how temperatures have changed over time.",
  "implement":      "The school will implement a new grading system next semester.",
  "import":         "The country imports most of its energy resources from abroad.",
  "improve":        "Regular exercise can greatly improve your physical and mental health.",
  "include":        "The price includes breakfast and free Wi-Fi.",
  "increase":       "The population of the city has increased rapidly in recent years.",
  "indicate":       "Studies indicate that sleep deprivation affects memory.",
  "influence":      "Music can strongly influence a person's mood and emotions.",
  "inform":         "Please inform the office if you plan to be absent.",
  "investigate":    "Police are investigating the cause of the fire.",
  "involve":        "The project involves cooperation between several departments.",
  "justify":        "Can you justify why you made that decision?",
  "launch":         "The tech company launched its new smartphone last week.",
  "limit":          "The teacher limited each presentation to five minutes.",
  "maintain":       "It is important to maintain a healthy diet throughout your life.",
  "manage":         "Despite the difficulties, she managed to finish the report on time.",
  "manufacture":    "The factory manufactures thousands of products each day.",
  "measure":        "Scientists measured the temperature at the bottom of the ocean.",
  "modify":         "You can modify the design to better suit your needs.",
  "motivate":       "A good teacher can motivate students to love learning.",
  "negotiate":      "The two countries negotiated a new trade agreement.",
  "obtain":         "You need to obtain permission before taking any photos here.",
  "operate":        "The machine is easy to operate once you read the manual.",
  "oppose":         "Many citizens opposed the plan to build a new highway.",
  "organize":       "She organized the event from start to finish.",
  "overcome":       "He overcame many obstacles to achieve his dream.",
  "participate":    "All students are encouraged to participate in school activities.",
  "perform":        "The orchestra performed beautifully at the concert.",
  "permit":         "Visitors are not permitted to take photographs inside the museum.",
  "persuade":       "She persuaded her parents to let her study abroad.",
  "predict":        "It is difficult to predict exactly when the earthquake will occur.",
  "prepare":        "He spent weeks preparing for the university entrance exam.",
  "present":        "She presented her research findings to the class.",
  "prevent":        "Washing your hands frequently can prevent the spread of illness.",
  "produce":        "This farm produces over 10,000 liters of milk per day.",
  "promote":        "The campaign aims to promote healthy eating among teenagers.",
  "propose":        "She proposed a new solution to the city's traffic problem.",
  "protect":        "We must protect the natural environment for future generations.",
  "provide":        "The school provides free meals for students from low-income families.",
  "publish":        "Her first novel was published when she was only 22 years old.",
  "purchase":       "You can purchase tickets online or at the box office.",
  "realize":        "I suddenly realized that I had left my wallet at home.",
  "recognize":      "The government finally recognized the importance of mental health.",
  "reduce":         "The company is trying to reduce its carbon emissions.",
  "refer":          "Please refer to the glossary at the back of the textbook.",
  "reject":         "His application was rejected because it was submitted too late.",
  "replace":        "The old bridge will be replaced with a modern one.",
  "represent":      "The flag represents the country's history and values.",
  "require":        "This job requires strong communication skills.",
  "research":       "She researched the topic thoroughly before writing the essay.",
  "resolve":        "The two sides finally resolved their dispute peacefully.",
  "respond":        "Please respond to the email as soon as possible.",
  "restrict":       "Access to the area was restricted after the accident.",
  "reveal":         "The survey revealed that most students prefer online learning.",
  "solve":          "We need to work together to solve this problem.",
  "submit":         "Please submit your assignment by Friday.",
  "suggest":        "He suggested taking a different route to avoid traffic.",
  "support":        "Friends and family supported her throughout her recovery.",
  "survive":        "The plants were able to survive the cold winter.",
  "transfer":       "She transferred to a new school in April.",
  "transform":      "The renovation transformed the old building into a modern café.",
  "treat":          "The doctor treated the patient's injury quickly.",
  "update":         "Make sure to update your software regularly for security.",
  "vary":           "Prices vary depending on the season and location.",
  "waste":          "Don't waste food — there are people who don't have enough to eat.",
  "withdraw":       "He decided to withdraw from the competition due to injury.",
  "abolish":        "The law was abolished after years of public protest.",
  "absorb":         "Sponges are designed to absorb water quickly.",
  "accommodate":    "The hotel can accommodate up to 500 guests at one time.",
  "acknowledge":    "The company acknowledged the mistake and apologized to customers.",
  "activate":       "Press the button to activate the alarm system.",
  "adhere":         "All members must adhere to the rules of the organization.",
  "administer":     "A nurse will administer the vaccine at the clinic.",
  "advocate":       "The organization advocates for the rights of working people.",
  "allocate":       "The government allocated extra funds to education this year.",
  "alter":          "The plan was altered due to bad weather.",
  "appeal":         "The lawyer decided to appeal the court's decision.",
  "assess":         "Teachers assess students' progress through regular tests.",
  "associate":      "People often associate the color red with danger.",
  "authorize":      "Only the manager is authorized to approve the budget.",
  "categorize":     "Please categorize the files into folders for easy access.",
  "compile":        "She compiled a list of all the resources she needed.",
  "coordinate":     "He coordinates the schedule for the entire team.",
  "customize":      "You can customize the settings to fit your preferences.",
  "dedicate":       "She dedicated many years of her life to teaching.",
  "delegate":       "A good leader knows how to delegate tasks effectively.",
  "derive":         "Many English words are derived from Latin or Greek.",
  "determine":      "The test results will determine which class you join.",
  "devote":         "He devoted himself to helping others in the community.",
  "differentiate":  "It can be hard to differentiate between the two products.",
  "diminish":       "Over time, the pain slowly diminished.",
  "document":       "It is important to document all changes made to the system.",
  "dominate":       "One company has dominated the market for decades.",
  "enable":         "Technology enables people to work from anywhere in the world.",
  "engage":         "The teacher found creative ways to engage the students.",
  "enhance":        "Adding fresh herbs can enhance the flavor of the dish.",
  "exchange":       "We exchanged contact information after the conference.",
  "facilitate":     "A good moderator can facilitate a productive discussion.",
  "gather":         "Hundreds of people gathered in the park to celebrate.",
  "incorporate":    "The new design incorporates both style and function.",
  "integrate":      "The school aims to integrate technology into everyday learning.",
  "interpret":      "The results can be interpreted in different ways.",
  "locate":         "Can you help me locate the nearest bus stop?",
  "monitor":        "Doctors monitor patients' heart rates during surgery.",
  "perceive":       "How you perceive a problem affects how you solve it.",
  "preserve":       "We must preserve the rainforest for future generations.",
  "prioritize":     "She learned to prioritize her health over her work.",
  "pursue":         "He decided to pursue a career in medicine.",
  "reinforce":      "Positive feedback reinforces good behavior in children.",
  "release":        "The artist released her new album last Friday.",
  "rely":           "In an emergency, people rely on quick communication.",
  "select":         "Carefully select the words you use in a formal email.",
  "separate":       "Please separate the recyclable items from the general waste.",
  "specify":        "Please specify the date and time of your arrival.",
  "stabilize":      "The new policy helped to stabilize the economy.",
  "strengthen":     "Regular exercise strengthens both your muscles and bones.",
  "track":          "The app helps you track your daily fitness goals.",
  "utilize":        "We should utilize all available resources efficiently.",
  "validate":       "The experiment was repeated to validate the findings.",
  "comprehend":     "It took me a while to fully comprehend the instructions.",
  "elaborate":      "Could you elaborate on your idea a little more?",
  "fluctuate":      "The price of oil tends to fluctuate with global events.",
  "formulate":      "The team formulated a clear plan before the meeting.",
  "generalize":     "You shouldn't generalize based on just a few examples.",
  "initiate":       "She initiated the project by bringing everyone together.",
  "neutralize":     "Baking soda can neutralize the acid in some cleaning products.",
  "optimize":       "Engineers are working to optimize the engine for fuel efficiency.",
  "rationalize":    "He tried to rationalize his decision, but it didn't make sense.",
  "simplify":       "Let's simplify the process so everyone can understand it.",
  "standardize":    "The company standardized its procedures across all offices.",
  "symbolize":      "The dove symbolizes peace in many cultures.",
  "undermine":      "Constant criticism can undermine a person's confidence.",
  "violate":        "Parking here violates the local traffic regulations.",
  "withstand":      "This building was designed to withstand strong earthquakes.",
  "aggregate":      "The data was aggregated from multiple sources.",
  "anticipate":     "We anticipate that demand will increase over the next year.",
  "clarify":        "Could you clarify what you mean by that statement?",
  "compensate":     "The company offered to compensate customers for the delay.",
  "comply":         "All employees must comply with the company's safety rules.",
  "conform":        "The building must conform to the local safety standards.",
  "contaminate":    "Industrial waste can contaminate rivers and water supplies.",
  "convert":        "The old warehouse was converted into modern apartments.",
  "degrade":        "Pollution can degrade the quality of the soil over time.",
  "diagnose":       "The doctor diagnosed the patient with a mild infection.",
  "discriminate":   "It is illegal to discriminate against workers based on age.",
  "enforce":        "The police enforce traffic laws to keep roads safe.",
  "exploit":        "Some companies exploit workers by paying very low wages.",
  "inspire":        "Her story inspired thousands of young people to follow their dreams.",
  "mobilize":       "The charity mobilized volunteers across the country.",
  "neglect":        "Neglecting regular maintenance can lead to bigger problems later.",
  "observe":        "Scientists observed the animal's behavior in its natural habitat.",
  "reconstruct":    "Historians tried to reconstruct events from ancient records.",
  "reinstate":      "The athlete was reinstated after a thorough investigation.",
  "renew":          "Don't forget to renew your passport before it expires.",
  "stimulate":      "Reading widely can stimulate your imagination and creativity.",
  "substitute":     "You can substitute honey for sugar in this recipe.",
  "sustain":        "It is hard to sustain a healthy lifestyle without good habits.",
  "underestimate":  "Never underestimate the power of consistent effort.",
  "alleviate":      "Painkillers can alleviate discomfort but don't cure the cause.",
  "amplify":        "Social media can amplify both good and bad information rapidly.",
  "assert":         "She asserted her right to express her own opinion.",
  "confront":       "It takes courage to confront a problem rather than ignore it.",
  "impose":         "The government imposed stricter rules on air travel safety.",
  "induce":         "Too much stress can induce headaches and sleep problems.",
  "regulate":       "The agency regulates the safety of food and medicine.",
  "revolutionize":  "The internet revolutionized the way people communicate and work.",
  "sacrifice":      "Many athletes sacrifice personal time to train for competitions.",
  "upgrade":        "The software was upgraded to fix several security issues.",

  // ── Nouns ─────────────────────────────────────────────────────────────
  "ability":        "She has the ability to learn new languages very quickly.",
  "absence":        "His absence from school was noted by the teacher.",
  "access":         "Everyone should have access to clean water and education.",
  "accident":       "A serious accident on the highway caused a long traffic jam.",
  "achievement":    "Winning the prize was a great achievement for the young student.",
  "activity":       "Physical activity is important for maintaining good health.",
  "advantage":      "Speaking two languages gives you a great advantage in business.",
  "advice":         "She gave me some useful advice about studying for exams.",
  "agreement":      "The two countries signed a trade agreement last year.",
  "aid":            "The government sent emergency aid to the flood-affected region.",
  "aim":            "Her aim is to study at a top university after high school.",
  "alternative":    "If the train is delayed, you should consider an alternative route.",
  "analysis":       "A detailed analysis of the data showed some surprising results.",
  "announcement":   "The announcement of the new product surprised many people.",
  "anxiety":        "Many students experience anxiety before important exams.",
  "area":           "The library has a quiet study area for students.",
  "argument":       "They had a heated argument about the best solution.",
  "aspect":         "Communication is one of the most important aspects of teamwork.",
  "assistance":     "The elderly man required assistance crossing the street.",
  "atmosphere":     "The cozy atmosphere of the café made it a popular study spot.",
  "attitude":       "A positive attitude can make a big difference in your results.",
  "authority":      "The government has the authority to enforce traffic laws.",
  "awareness":      "Public awareness of climate change has grown significantly.",
  "benefit":        "One benefit of learning English is greater career opportunities.",
  "behavior":       "The student's behavior improved after talking with the counselor.",
  "career":         "She wants to pursue a career in international business.",
  "circumstance":   "Under normal circumstances, the process takes about a week.",
  "commitment":     "Success requires a strong commitment to regular practice.",
  "communication":  "Good communication is the key to a healthy relationship.",
  "competition":    "The competition this year was fiercer than anyone expected.",
  "condition":      "The athlete recovered quickly and is now in excellent condition.",
  "confidence":     "Public speaking classes helped him build his confidence.",
  "conflict":       "The conflict between the two groups lasted for many years.",
  "consequence":    "Cheating in an exam can have serious consequences.",
  "contribution":   "Her contribution to the project was recognized by everyone.",
  "controversy":    "The new policy caused a great deal of controversy online.",
  "cooperation":    "International cooperation is necessary to solve global problems.",
  "criticism":      "Constructive criticism can help you improve your work.",
  "culture":        "Studying abroad gives you the chance to experience a new culture.",
  "danger":         "Driving too fast is a danger to yourself and others.",
  "decision":       "Making the right decision takes time and careful thought.",
  "desire":         "She had a strong desire to make a difference in the world.",
  "development":    "The rapid development of technology has changed everyday life.",
  "difference":     "What is the main difference between these two options?",
  "difficulty":     "He overcame many difficulties to reach the top of his field.",
  "disadvantage":   "One disadvantage of city life is the high cost of living.",
  "discovery":      "The discovery of the new medicine gave hope to millions of people.",
  "diversity":      "Diversity in the workplace brings different perspectives and ideas.",
  "economy":        "The country's economy grew strongly in the past decade.",
  "education":      "Quality education is the foundation of a successful society.",
  "effect":         "The medicine had no negative effects on the patient.",
  "efficiency":     "Automation has greatly improved the efficiency of manufacturing.",
  "effort":         "With enough effort, you can achieve almost anything.",
  "element":        "Trust is an essential element of any good relationship.",
  "emergency":      "In an emergency, please call 110 or 119 immediately.",
  "emotion":        "Music has the power to stir deep emotions in listeners.",
  "emphasis":       "There is a strong emphasis on teamwork in Japanese companies.",
  "environment":    "We all have a responsibility to protect the natural environment.",
  "equality":       "The law was designed to promote equality for all citizens.",
  "error":          "Please check your work carefully to avoid any errors.",
  "evidence":       "There is strong evidence that exercise improves mental health.",
  "evolution":      "The evolution of smartphones has changed how we live.",
  "expectation":    "The performance exceeded everyone's expectations.",
  "experience":     "Working part-time gave her valuable real-world experience.",
  "explanation":    "The teacher gave a clear explanation of the new grammar rule.",
  "failure":        "Failure is not the end — it is often the beginning of success.",
  "flexibility":    "Flexibility in your schedule can reduce stress significantly.",
  "freedom":        "Freedom of speech is a fundamental right in a democracy.",
  "function":       "The main function of the heart is to pump blood through the body.",
  "goal":           "Set clear goals and work toward them every day.",
  "growth":         "Personal growth requires stepping outside your comfort zone.",
  "guideline":      "Follow the guidelines carefully to complete the task correctly.",
  "habit":          "Developing good study habits early will help you in the future.",
  "health":         "Your mental health is just as important as your physical health.",
  "impact":         "The new policy had a major impact on local businesses.",
  "improvement":    "There has been a clear improvement in the student's performance.",
  "income":         "A steady income allows people to plan for the future.",
  "independence":   "Moving abroad gave her a strong sense of independence.",
  "infrastructure": "Good infrastructure is essential for economic development.",
  "issue":          "Climate change is one of the most pressing issues of our time.",
  "knowledge":      "Knowledge gained through reading can open many doors.",
  "leadership":     "Strong leadership is needed to guide the team through challenges.",
  "limitation":     "Every approach has its limitations.",
  "media":          "The media plays an important role in shaping public opinion.",
  "method":         "Scientists use a variety of methods to test their theories.",
  "motivation":     "Finding your motivation is the first step toward achieving your goals.",
  "movement":       "The environmental movement has gained millions of supporters.",
  "necessity":      "Sleep is not a luxury — it is a necessity for good health.",
  "objective":      "The main objective of the project is to improve air quality.",
  "obstacle":       "Don't let small obstacles stop you from pursuing your goals.",
  "opportunity":    "Studying abroad is a wonderful opportunity to grow as a person.",
  "organization":   "She joined a non-profit organization that supports refugees.",
  "outcome":        "The outcome of the election surprised most political analysts.",
  "pattern":        "Scientists noticed a clear pattern in the data they collected.",
  "perception":     "Our perception of reality can be influenced by our experiences.",
  "performance":    "The athlete's performance improved after weeks of hard training.",
  "perspective":    "Traveling gives you a new perspective on your own country.",
  "phenomenon":     "Climate change is a global phenomenon that affects everyone.",
  "policy":         "The school introduced a new mobile phone policy.",
  "population":     "The world's population is expected to reach 10 billion by 2050.",
  "poverty":        "Many organizations work hard to reduce poverty worldwide.",
  "preference":     "What is your preference — coffee or tea?",
  "pressure":       "Students often feel pressure to perform well in exams.",
  "priority":       "Health should always be your top priority.",
  "progress":       "She made impressive progress in her English studies.",
  "property":       "Private property must be respected by everyone.",
  "proposal":       "The proposal to build a new library was approved by the council.",
  "protection":     "Wildlife protection is important to maintain biodiversity.",
  "purpose":        "What is the main purpose of this research?",
  "quality":        "We should never sacrifice quality for the sake of speed.",
  "reality":        "The reality of working life is often different from expectations.",
  "recognition":    "He finally received recognition for his years of hard work.",
  "relationship":   "A strong relationship is built on trust and communication.",
  "reputation":     "The company built its reputation for reliable customer service.",
  "requirement":    "Meeting the requirements for admission can be challenging.",
  "resource":       "Water is a precious natural resource that must be protected.",
  "responsibility": "Every citizen has a responsibility to keep their community clean.",
  "result":         "The results of the exam will be announced next week.",
  "safety":         "Road safety is everyone's responsibility.",
  "satisfaction":   "She felt great satisfaction after completing the marathon.",
  "shortage":       "There is a serious shortage of qualified nurses in many regions.",
  "significance":   "The historian explained the significance of the ancient ruins.",
  "situation":      "The situation improved after the team came up with a new strategy.",
  "skill":          "Good presentation skills are valuable in any career.",
  "solution":       "Finding a long-term solution to the problem will take time.",
  "standard":       "The school has high standards for both academic and personal conduct.",
  "strategy":       "The company adopted a new marketing strategy to increase sales.",
  "strength":       "Her greatest strength is her ability to stay calm under pressure.",
  "struggle":       "He shared his personal struggle with anxiety to help others.",
  "success":        "Success is the result of consistent effort and a positive mindset.",
  "technology":     "Technology has transformed nearly every aspect of modern life.",
  "tendency":       "There is a tendency for people to avoid difficult conversations.",
  "trend":          "The trend toward remote work has continued since the pandemic.",
  "variety":        "A variety of activities was offered at the summer camp.",
  "weakness":       "Knowing your weaknesses is the first step to overcoming them.",
  "welfare":        "The organization is dedicated to improving animal welfare.",
  "acquisition":    "The company's latest acquisition helped it enter new markets.",
  "adaptation":     "Adaptation to new environments is a key skill for modern workers.",
  "administration": "She works in the administration department at the university.",
  "advocacy":       "Her advocacy for education reform led to significant changes.",
  "allocation":     "Efficient allocation of resources is critical for any project.",
  "amendment":      "An amendment to the law was proposed to strengthen data privacy.",
  "appreciation":   "She expressed her appreciation for all the support she received.",
  "assumption":     "Don't make an assumption without checking the facts first.",
  "authorization":  "You need written authorization to access this area.",
  "capability":     "The new robot has the capability to perform complex tasks.",
  "category":       "Books are sorted by category to make them easy to find.",
  "collaboration":  "The project was a collaboration between universities in three countries.",
  "component":      "Each component of the machine plays an important role.",
  "concept":        "The concept of sustainability is central to modern urban planning.",
  "context":        "The meaning of a word often depends on its context.",
  "convention":     "It is convention to shake hands when meeting someone in business.",
  "correlation":    "Researchers found a strong correlation between diet and health.",
  "currency":       "The local currency dropped sharply against the dollar.",
  "declaration":    "The declaration of independence was signed in 1776.",
  "delivery":       "Fast and reliable delivery is essential for online businesses.",
  "democracy":      "A healthy democracy depends on an informed and active public.",
  "dimension":      "Space has three dimensions: length, width, and height.",
  "discipline":     "Strong discipline and focus are needed to excel in sports.",
  "distribution":   "The equal distribution of resources is a key goal of the policy.",
  "domain":         "She is considered an expert in the domain of environmental law.",
  "emission":       "Reducing carbon emissions is essential to fighting climate change.",
  "evaluation":     "A thorough evaluation of the plan revealed some weaknesses.",
  "factor":         "Diet and exercise are two important factors for staying healthy.",
  "feedback":       "Feedback from users helped the developers improve the app.",
  "finance":        "She studied finance and economics at a top university.",
  "framework":      "The government developed a new framework for reducing poverty.",
  "generation":     "Each generation faces its own unique set of challenges.",
  "governance":     "Good governance requires transparency and accountability.",
  "hypothesis":     "The scientist tested his hypothesis through careful experiments.",
  "identity":       "Living abroad made her think more deeply about her cultural identity.",
  "implementation": "The implementation of the new system went smoothly.",
  "integration":    "The integration of AI into everyday products is accelerating.",
  "interpretation": "There is more than one valid interpretation of this poem.",
  "intervention":   "Early intervention is key to preventing serious health issues.",
  "investment":     "Investing in education is one of the best investments you can make.",
  "labor":          "The factory depends on a large and skilled labor force.",
  "legislation":    "New legislation was passed to protect consumer data.",
  "mechanism":      "Scientists are studying the mechanism behind this disease.",
  "monitoring":     "Continuous monitoring of air quality helps detect pollution early.",
  "network":        "A strong professional network can help you find new opportunities.",
  "optimization":   "Optimization of the delivery routes reduced costs by 20%.",
  "output":         "The factory's output increased significantly this quarter.",
  "participant":    "Every participant in the study signed a consent form.",
  "philosophy":     "His philosophy is simple: work hard and be kind to others.",
  "procedure":      "Follow the standard procedure to ensure safety in the lab.",
  "profit":         "The company reported a record profit in its annual report.",
  "project":        "The student completed her science project in just three days.",
  "provision":      "The new agreement includes provisions for dispute resolution.",
  "ratio":          "The ratio of students to teachers in this school is 25 to 1.",
  "regulation":     "New regulations were introduced to reduce food waste.",
  "restriction":    "There are restrictions on how many people can enter at one time.",
  "revenue":        "The company's revenue grew by 15% compared to last year.",
  "risk":           "There is always some risk involved in starting a new business.",
  "scenario":       "In a worst-case scenario, the entire event could be canceled.",
  "sector":         "The technology sector is one of the fastest-growing industries.",
  "sequence":       "Make sure to follow the steps in the correct sequence.",
  "statistics":     "Statistics show that young people are spending more time online.",
  "structure":      "A clear structure is essential when writing an essay.",
  "sustainability": "Sustainability should be at the heart of every business decision.",
  "transformation": "The transformation of the neighborhood was remarkable.",
  "transition":     "The transition from high school to university can be challenging.",
  "unemployment":   "The government introduced new measures to tackle unemployment.",
  "variation":      "There is a lot of variation in the prices of goods across regions.",
  "workforce":      "Companies need to invest in their workforce to stay competitive.",
  "accomplishment": "Graduating early was her greatest personal accomplishment.",
  "adolescent":     "Adolescents need both independence and guidance from adults.",
  "affluence":      "The affluence of the neighborhood was visible in its large homes.",
  "aftermath":      "In the aftermath of the storm, thousands of people needed help.",
  "agenda":         "The main item on the agenda was the new budget proposal.",
  "ambition":       "Her ambition is to start her own company before the age of 30.",
  "apprehension":   "There was a sense of apprehension before the results were announced.",
  "asset":          "A positive attitude is a valuable asset in any workplace.",
  "automation":     "Automation has replaced many repetitive jobs in manufacturing.",
  "autonomy":       "Students are given greater autonomy in their final year.",
  "backlash":       "The new policy received a strong backlash from the public.",
  "benchmark":      "The school uses national test scores as a benchmark.",
  "bias":           "Journalists should be aware of their own bias when writing.",
  "breakdown":      "The breakdown in communication led to a serious misunderstanding.",
  "bureaucracy":    "The application process involves a lot of bureaucracy.",
  "capacity":       "The stadium has a capacity of 60,000 spectators.",
  "competence":     "The position requires a high level of linguistic competence.",
  "complication":   "The surgery went well, with no complications.",
  "consciousness":  "Environmental consciousness has grown among young people.",
  "constraint":     "Budget constraints made it difficult to expand the project.",
  "corruption":     "Corruption in the government was exposed by investigative journalists.",
  "creativity":     "Creativity is one of the most valued skills in today's economy.",
  "credibility":    "Providing accurate sources adds credibility to your argument.",
  "crisis":         "The country faced an economic crisis during the global downturn.",
  "criterion":      "The main criterion for selection is academic achievement.",
  "curiosity":      "Curiosity drives scientists to ask new questions and explore.",
  "dedication":     "Her dedication to her craft made her one of the best in her field.",
  "deficiency":     "A vitamin D deficiency can cause fatigue and bone problems.",
  "demographic":    "The demographic of the city has changed significantly over 20 years.",
  "dependency":     "There is growing concern about teenagers' dependency on social media.",
  "deterioration":  "The deterioration of the building made it unsafe to enter.",
  "dignity":        "Every person deserves to be treated with respect and dignity.",
  "disruption":     "The power cut caused a major disruption to business operations.",
  "dominance":      "The team's dominance in the league was clear from the first match.",
  "drawback":       "One major drawback of city life is the noise and pollution.",
  "eligibility":    "You must meet the eligibility requirements before applying.",
  "engagement":     "Student engagement in the classroom has improved greatly.",
  "epidemic":       "Health officials acted quickly to contain the epidemic.",
  "exclusion":      "Social exclusion can have a serious impact on mental health.",
  "exploitation":   "The documentary exposed the exploitation of workers overseas.",
  "exposure":       "Regular exposure to English helps you improve your fluency.",
  "fluctuation":    "Investors must be prepared for fluctuations in the stock market.",
  "gap":            "The gap between the rich and the poor continues to widen.",
  "globalization":  "Globalization has made it easier to trade with countries worldwide.",
  "hierarchy":      "The company has a strict hierarchy, with the CEO at the top.",
  "hostility":      "There was a great deal of hostility between the two groups.",
  "ideology":       "Political parties are often guided by a particular ideology.",
  "imbalance":      "An imbalance of nutrients can affect your overall health.",
  "inclusion":      "The school promotes inclusion for students with disabilities.",
  "inequality":     "Income inequality is a growing concern in many developed nations.",
  "initiative":     "The recycling initiative helped reduce waste in the community.",
  "innovation":     "Innovation in renewable energy is accelerating worldwide.",
  "insight":        "His deep insight into human behavior made him an excellent writer.",
  "integrity":      "A person of integrity does the right thing even when no one is watching.",
  "interaction":    "Face-to-face interaction is essential for building trust.",
  "justification":  "There is no justification for treating people unfairly.",
  "liability":      "The company accepted liability for the damage caused.",
  "mediation":      "Mediation helped the two sides reach an agreement without going to court.",
  "minority":       "The rights of minority groups must be respected in a democracy.",
  "modernization":  "The modernization of the transport network is long overdue.",
  "morale":         "The manager's words of encouragement boosted team morale.",
  "negotiation":    "Successful negotiation requires patience and good listening.",
  "norm":           "It has become the norm to check your phone first thing in the morning.",
  "obligation":     "You have an obligation to return the borrowed book on time.",
  "oppression":     "The protesters spoke out against the oppression of minorities.",
  "penalty":        "The penalty for late submission is a reduction in your grade.",
  "polarization":   "Political polarization has made it difficult to reach compromise.",
  "potential":      "Every student has the potential to succeed with the right support.",
  "privilege":      "Having access to quality education is a privilege not everyone enjoys.",
  "progression":    "The progression of the disease was slower than doctors expected.",
  "prosperity":     "Education and hard work are keys to long-term prosperity.",
  "rationality":    "Decisions should be based on rationality, not emotion alone.",
  "reform":         "The education reform gave more flexibility to local schools.",
  "reliability":    "The reliability of the data is crucial for the research.",
  "resilience":     "Resilience is the ability to recover quickly from difficulties.",
  "resolution":     "The dispute was settled through a peaceful resolution.",
  "rhetoric":       "His speech was full of powerful rhetoric that inspired the crowd.",
  "solidarity":     "The community showed great solidarity after the natural disaster.",
  "sovereignty":    "The nation's sovereignty must be respected by other countries.",
  "spectrum":       "The film appeals to a wide spectrum of audiences.",
  "stereotype":     "Breaking stereotypes is important for creating an equal society.",
  "stimulus":       "Exercise is a powerful stimulus for both body and mind.",
  "subordinate":    "As a new employee, she was a subordinate to the department head.",
  "superiority":    "She showed clear superiority in the final round of the competition.",
  "suppression":    "The suppression of free speech is a serious human rights violation.",
  "tolerance":      "Tolerance and respect are the foundations of a peaceful society.",
  "transparency":   "The public demands greater transparency from elected officials.",
  "trauma":         "The survivors of the disaster required counseling to deal with trauma.",
  "uncertainty":    "There is still much uncertainty about the long-term effects.",
  "unity":          "The disaster brought the community together in unity.",
  "validity":       "The validity of the research depends on the accuracy of the data.",
  "vulnerability":  "Showing vulnerability takes courage and builds trust.",
  "catalyst":       "The new technology acted as a catalyst for rapid social change.",
  "momentum":       "The team built up momentum after scoring three goals in a row.",
  "precedent":      "The court's ruling set a precedent for future cases.",
  "repercussion":   "The decision had serious repercussions for the entire industry.",
  "breakthrough":   "The new vaccine was hailed as a major medical breakthrough.",
  "milestone":      "Graduating from university was an important milestone in her life.",
  "pitfall":        "Be aware of the common pitfalls when starting a new business.",
  "endeavor":       "Learning a new language is a challenging but rewarding endeavor.",
  "foundation":     "Hard work and curiosity are the foundation of academic success.",
  "incentive":      "Offering bonuses is a common incentive to improve performance.",
  "implication":    "Consider the implications of your decision before acting.",
  "misconception":  "A common misconception is that you don't need to sleep enough.",
  "contradiction":  "There is a contradiction between what he says and what he does.",
  "revelation":     "The revelation of the test results came as a complete surprise.",
  "paradox":        "It's a paradox that we feel lonelier in a more connected world.",
  "dilemma":        "She faced a dilemma: stay at home or accept the job overseas.",
  "consensus":      "The committee reached a consensus after several hours of discussion.",
  "compromise":     "A compromise was reached that satisfied both sides.",
  "enthusiasm":     "The students showed great enthusiasm for the science experiment.",
  "compassion":     "Showing compassion toward others is a sign of true strength.",
  "prejudice":      "We must work to eliminate prejudice in all its forms.",

  // ── Adjectives ──────────────────────────────────────────────────────────
  "abundant":       "Fish and seafood are abundant in coastal regions.",
  "accurate":       "Always make sure your information is accurate before sharing it.",
  "adequate":       "Make sure you get adequate sleep before an important test.",
  "appropriate":    "Please wear appropriate clothing for the formal event.",
  "available":      "The manager is available for meetings on Thursday morning.",
  "aware":          "Are you aware of the risks involved in this activity?",
  "capable":        "She is fully capable of managing the project on her own.",
  "certain":        "I am not certain about the answer, so let me check again.",
  "comfortable":    "The hotel room was comfortable and had a great view.",
  "complex":        "The situation became more complex as new information emerged.",
  "confident":      "Be confident in your abilities and trust your preparation.",
  "considerable":   "The project required a considerable amount of time and effort.",
  "consistent":     "Consistent practice is the key to mastering any skill.",
  "controversial":  "The proposed change to the school system was highly controversial.",
  "convenient":     "Living near a train station is very convenient for commuters.",
  "creative":       "She came up with a highly creative solution to the design problem.",
  "critical":       "Critical thinking is an essential skill for university study.",
  "decisive":       "A good leader must be decisive in times of crisis.",
  "determined":     "He was determined to pass the exam, no matter how hard it was.",
  "diverse":        "The school has a diverse community of students from many countries.",
  "effective":      "Regular revision is one of the most effective study techniques.",
  "efficient":      "An efficient worker can complete tasks without wasting time.",
  "essential":      "Water and food are essential for human survival.",
  "evident":        "It was evident from the beginning that she had great talent.",
  "excessive":      "Excessive use of smartphones can affect concentration.",
  "flexible":       "A flexible schedule allows you to manage your time better.",
  "fundamental":    "Understanding grammar is fundamental to learning any language.",
  "genuine":        "She showed genuine interest in the topic during the lesson.",
  "global":         "Climate change is a global problem that requires global solutions.",
  "gradual":        "The recovery was slow but gradual over several months.",
  "harmful":        "Eating too much sugar can be harmful to your teeth and health.",
  "immediate":      "The situation required an immediate response from the authorities.",
  "independent":    "Independent research shows that exercise boosts brain function.",
  "inevitable":     "Change is inevitable — it is how we respond that matters.",
  "influential":    "She became one of the most influential scientists of her generation.",
  "innovative":     "The company is known for its innovative approach to product design.",
  "limited":        "Resources are limited, so we must use them wisely.",
  "logical":        "His argument was logical and well-supported by evidence.",
  "loyal":          "A loyal friend will support you even in difficult times.",
  "mature":         "She is mature for her age and handles responsibilities well.",
  "meaningful":     "Volunteering gave her a sense of meaningful purpose.",
  "moderate":       "A moderate amount of exercise every day keeps you healthy.",
  "motivated":      "Students who are motivated tend to achieve better results.",
  "mutual":         "The deal was based on mutual trust and respect.",
  "negative":       "Negative thinking can become a barrier to success.",
  "neutral":        "Switzerland has traditionally maintained a neutral position in wars.",
  "obvious":        "It was obvious that he hadn't prepared for the presentation.",
  "ordinary":       "She turned an ordinary day into something memorable.",
  "original":       "The writer was praised for her original and imaginative style.",
  "outstanding":    "His outstanding performance earned him a scholarship.",
  "passionate":     "She is passionate about helping others and often volunteers.",
  "persistent":     "Persistent effort over time leads to significant improvement.",
  "physical":       "Physical fitness plays an important role in overall well-being.",
  "political":      "Young people are becoming more politically engaged than ever.",
  "positive":       "Try to maintain a positive mindset even when things are tough.",
  "practical":      "Her advice was practical and easy to apply in real life.",
  "precise":        "Please be precise in your measurements to ensure accuracy.",
  "productive":     "Working in a quiet environment makes me much more productive.",
  "professional":   "She always behaves in a professional manner at work.",
  "prominent":      "He became a prominent figure in the environmental movement.",
  "reasonable":     "The teacher's expectations were firm but reasonable.",
  "relevant":       "Make sure your answer is relevant to the question being asked.",
  "reliable":       "A reliable source of information is essential for research.",
  "remarkable":     "The student made remarkable progress in just one semester.",
  "responsible":    "We must be responsible with the natural resources we use.",
  "significant":    "There has been a significant improvement in air quality recently.",
  "specific":       "Please give a specific example to support your argument.",
  "stable":         "A stable environment helps children develop confidence.",
  "suitable":       "Choose a topic that is suitable for the target audience.",
  "sustainable":    "We need to find more sustainable alternatives to fossil fuels.",
  "technical":      "Some parts of the manual use technical language that can be confusing.",
  "temporary":      "The road closure is temporary and will last only a week.",
  "traditional":    "The festival celebrates traditional music and food.",
  "typical":        "A typical day for her starts with a 30-minute run.",
  "unique":         "Every person has a unique set of skills and experiences.",
  "vital":          "Fresh air and clean water are vital for life.",
  "voluntary":      "The work is entirely voluntary — no one is forced to participate.",
  "academic":       "She received an academic scholarship to study at the university.",
  "accessible":     "The app is designed to be accessible for users of all ages.",
  "active":         "An active lifestyle helps reduce the risk of many diseases.",
  "adaptive":       "Adaptive technologies help people with disabilities communicate.",
  "affordable":     "The goal is to make quality healthcare affordable for everyone.",
  "aggressive":     "The company took an aggressive approach to expanding its market share.",
  "analytical":     "She has strong analytical skills and enjoys solving complex problems.",
  "autonomous":     "Autonomous vehicles are being tested in many cities.",
  "beneficial":     "Exercise is beneficial for both the body and the mind.",
  "collective":     "Protecting the environment is a collective responsibility.",
  "commercial":     "The commercial success of the film was beyond anyone's expectations.",
  "compatible":     "Make sure the new software is compatible with your operating system.",
  "competitive":    "The job market has become increasingly competitive.",
  "comprehensive":  "The report provides a comprehensive overview of the current situation.",
  "continuous":     "Continuous improvement is the goal of any serious student.",
  "cooperative":    "The class was cooperative and worked well as a team.",
  "corporate":      "Corporate social responsibility is important to modern consumers.",
  "cultural":       "Cultural exchange programs help build understanding between nations.",
  "democratic":     "The country transitioned to a more democratic form of government.",
  "digital":        "The digital age has transformed how we access information.",
  "diplomatic":     "A diplomatic response can help avoid unnecessary conflict.",
  "dominant":       "One company is dominant in the smartphone market.",
  "economic":       "Economic growth alone is not enough — we need sustainable development.",
  "educational":    "The museum offers educational programs for school groups.",
  "environmental":  "We need stronger environmental regulations to protect nature.",
  "ethical":        "Ethical companies treat both their workers and environment well.",
  "extensive":      "She conducted extensive research before writing her thesis.",
  "external":       "External pressure from investors led to a change in management.",
  "formal":         "A formal letter of application is required for the position.",
  "functional":     "The design is sleek and fully functional for everyday use.",
  "governmental":   "Several governmental agencies are involved in the process.",
  "historical":     "This is a site of great historical significance.",
  "identical":      "The twins looked identical but had very different personalities.",
  "industrial":     "Industrial pollution remains a major environmental challenge.",
  "intellectual":   "Reading widely helps develop your intellectual curiosity.",
  "intensive":      "The students completed an intensive English course over the summer.",
  "intermediate":   "The course is designed for intermediate-level students.",
  "internal":       "The company launched an internal review after the incident.",
  "legislative":    "The legislative branch is responsible for making laws.",
  "marginal":       "The improvement in the results was marginal at best.",
  "monetary":       "The government introduced new monetary policies to control inflation.",
  "moral":          "It is our moral duty to help those less fortunate than ourselves.",
  "multinational":  "Multinational companies operate in dozens of countries simultaneously.",
  "numerical":      "Please provide a numerical answer rather than a description.",
  "organic":        "Organic farming avoids the use of artificial pesticides.",
  "popular":        "The new café became popular with students almost immediately.",
  "rational":       "Try to make a rational decision rather than acting on emotion.",
  "regional":       "Regional dialects can differ greatly from standard English.",
  "regulatory":     "All products must meet regulatory standards before being sold.",
  "robust":         "The system has a robust security protocol to prevent hacking.",
  "secondary":      "Preventing illness is a primary goal; treatment is secondary.",
  "sensitive":      "Be sensitive to other people's feelings when giving feedback.",
  "sophisticated":  "The new camera has a sophisticated set of automated features.",
  "statistical":    "The statistical analysis confirmed the researchers' hypothesis.",
  "strategic":      "A strategic partnership can help both companies grow faster.",
  "structural":     "Engineers examined the structural damage after the earthquake.",
  "substantial":    "The company invested a substantial amount in research and development.",
  "systematic":     "A systematic approach to studying will yield better results.",
  "transparent":    "The organization aims to be transparent in all its operations.",
  "universal":      "Education is considered a universal human right.",
  "urban":          "Urban areas tend to have better access to healthcare facilities.",
  "valuable":       "Time management is a valuable skill for students and professionals.",
  "diligent":       "A diligent student reviews their notes every day.",
  "eloquent":       "She gave an eloquent speech that moved everyone in the audience.",
  "ambiguous":      "The instructions were ambiguous, so many students were confused.",
  "concise":        "A good essay is concise and avoids unnecessary repetition.",
  "vulnerable":     "Children and the elderly are most vulnerable during a heat wave.",
  "optimistic":     "Despite the challenges, she remained optimistic about the future.",
  "pessimistic":    "Try not to be pessimistic — focus on what you can do.",
  "indifferent":    "He seemed indifferent to the outcome of the discussion.",
  "reluctant":      "She was reluctant to speak in public at first.",
  "skeptical":      "Many scientists are skeptical about the claimed results.",
  "ambitious":      "She is ambitious and determined to reach the top of her career.",
  "courageous":     "It takes a courageous person to stand up for what is right.",
  "humble":         "Despite her success, she remained humble and approachable.",
  "arrogant":       "His arrogant attitude made it difficult for others to work with him.",
  "tolerant":       "A tolerant society respects people of all backgrounds and beliefs.",
  "stubborn":       "He was so stubborn that he refused to listen to advice.",
  "generous":       "She was generous enough to donate all her prize money to charity.",
  "sympathetic":    "The counselor was sympathetic and listened carefully to her problems.",
  "passive":        "A passive approach rarely leads to the results you want.",
  "proactive":      "Being proactive means taking action before problems arise.",
  "objective":      "Try to be objective when evaluating your own work.",
  "subjective":     "Beauty is largely subjective — it depends on personal taste.",
  "abstract":       "Abstract concepts like justice can be difficult to define.",
  "concrete":       "Please provide a concrete example to clarify your point.",
  "explicit":       "The rules must be made explicit so everyone understands them.",
  "implicit":       "There is an implicit understanding that punctuality is important.",
  "inherent":       "There is an inherent risk in any type of financial investment.",
  "arbitrary":      "The decision felt arbitrary and was not based on any clear rules.",
  "spontaneous":    "The spontaneous applause surprised the speaker.",
  "deliberate":     "The mistake was deliberate, not accidental.",
  "domestic":       "The rise in domestic tourism has helped local businesses.",
  "foreign":        "She has always been fascinated by foreign languages and cultures.",
  "annual":         "The annual sports day is one of the most popular school events.",
  "contemporary":   "The museum features both classical and contemporary art.",
  "conventional":   "The conventional approach may not work in this unique situation.",
  "notorious":      "The company became notorious for its poor environmental record.",
  "legitimate":     "She had a legitimate reason for being late to the exam.",
  "feasible":       "The plan sounds exciting, but is it financially feasible?",
  "plausible":      "His explanation was plausible enough to be taken seriously.",
  "credible":       "You need credible evidence to support your claim.",
  "coherent":       "A well-written essay should have a coherent and logical structure.",
  "urgent":         "The medical team acted quickly in response to the urgent situation.",
  "enormous":       "The earthquake caused enormous damage to the city.",
  "profound":       "Her experience abroad had a profound impact on her worldview.",
  "subtle":         "There is a subtle difference in meaning between these two words.",
  "valid":          "Your argument is interesting, but is it valid without evidence?",

  // ── Adverbs ────────────────────────────────────────────────────────────
  "absolutely":     "I absolutely agree with your suggestion.",
  "additionally":   "The project requires time and effort; additionally, it needs funding.",
  "apparently":     "Apparently, the event was cancelled due to bad weather.",
  "approximately":  "The trip will take approximately three hours by train.",
  "certainly":      "She certainly has the talent to become a professional musician.",
  "clearly":        "The teacher explained the rule clearly and gave several examples.",
  "commonly":       "This phrase is commonly used in formal writing.",
  "completely":     "I completely forgot about the meeting — I'm so sorry.",
  "consistently":   "She consistently achieves top marks in all her subjects.",
  "continuously":   "The machine runs continuously without stopping.",
  "currently":      "The library is currently undergoing renovation.",
  "definitely":     "I definitely want to visit Japan again someday.",
  "effectively":    "She used her time effectively and finished the work ahead of schedule.",
  "especially":     "I especially enjoy learning new vocabulary in English class.",
  "essentially":    "The two plans are essentially the same with minor differences.",
  "eventually":     "She struggled at first, but eventually passed the exam.",
  "exactly":        "That is exactly what I was trying to say — thank you.",
  "frequently":     "He frequently forgets to bring his textbook to class.",
  "generally":      "Generally speaking, regular exercise is good for your health.",
  "gradually":      "Her confidence grew gradually over the course of the year.",
  "highly":         "The teacher was highly impressed by the quality of the work.",
  "increasingly":   "People are increasingly aware of the importance of mental health.",
  "individually":   "The students submitted their work individually.",
  "initially":      "Initially, the project seemed very difficult, but it became easier.",
  "largely":        "The success of the event was largely due to the volunteers.",
  "mainly":         "Her research focuses mainly on renewable energy.",
  "moreover":       "The price is reasonable; moreover, the quality is excellent.",
  "nearly":         "I nearly missed the train because of the traffic.",
  "obviously":      "She was obviously nervous during her first public speech.",
  "particularly":   "This topic is particularly important for students taking the exam.",
  "perfectly":      "The dress fit her perfectly and looked stunning.",
  "practically":    "Practically everyone in the class passed the test.",
  "precisely":      "That is precisely the point I was trying to make.",
  "primarily":      "The article is primarily aimed at university students.",
  "probably":       "It will probably rain tomorrow, so bring an umbrella.",
  "properly":       "Make sure you wash your hands properly before eating.",
  "rapidly":        "The situation changed rapidly as new information became available.",
  "rarely":         "She rarely makes the same mistake twice.",
  "reasonably":     "The hotel is reasonably priced for the level of service it offers.",
  "recently":       "I recently started going to the gym three times a week.",
  "regularly":      "Review your notes regularly to improve retention.",
  "relatively":     "The new system is relatively easy to learn.",
  "repeatedly":     "He was warned repeatedly not to park in that area.",
  "significantly":  "Test scores improved significantly after the new program was introduced.",
  "simply":         "The answer is simply to practice as much as possible.",
  "specifically":   "The rule applies specifically to students in their final year.",
  "slightly":       "The temperature was slightly higher than expected.",
  "strongly":       "She strongly believes that education can change the world.",
  "suddenly":       "The sky suddenly turned dark and it began to rain.",
  "temporarily":    "The service was temporarily suspended due to maintenance.",
  "typically":      "Typically, the process takes around two weeks.",
  "ultimately":     "Ultimately, it is your decision and you must own the result.",
  "usually":        "I usually wake up at six o'clock on school days.",
  "virtually":      "Virtually all the students in the class passed the test.",
  "widely":         "This approach is widely used in language teaching.",
  "accordingly":    "We changed our plans accordingly when the weather turned bad.",
  "alternatively":  "You can submit the form online; alternatively, hand it in at the office.",
  "consequently":   "He didn't study enough; consequently, he failed the test.",
  "deliberately":   "She deliberately spoke slowly so everyone could understand.",
  "dramatically":   "The number of online shoppers has increased dramatically.",
  "extensively":    "The topic has been extensively studied by researchers worldwide.",
  "fundamentally":  "The two approaches are fundamentally different.",
  "literally":      "The store was literally empty when I arrived.",
  "logically":      "If we think about this logically, the answer becomes clear.",
  "naturally":      "Naturally, parents want the best for their children.",
  "necessarily":    "Being busy doesn't necessarily mean being productive.",
  "notably":        "Several students, notably those in Year 3, performed exceptionally well.",
  "previously":     "The building was previously used as a hospital.",
  "radically":      "Technology has radically changed how people communicate.",
  "remarkably":     "The student's progress was remarkably fast.",
  "technically":    "Technically, both answers are correct.",
  "traditionally":  "Traditionally, the festival is held in the first week of May.",

  // ── Idioms & Phrases ──────────────────────────────────────────────────────
  "account for":        "How do you account for the sudden drop in sales?",
  "adapt to":           "It takes time to adapt to a new culture and environment.",
  "apply for":          "I plan to apply for a part-time job over the summer.",
  "as a result":        "He studied hard every day; as a result, he passed the exam.",
  "at the same time":   "She was studying and working at the same time.",
  "be aware of":        "You should be aware of the risks before making a decision.",
  "be based on":        "The movie is based on a true story.",
  "be concerned about": "Many people are concerned about the effects of climate change.",
  "be responsible for": "Each student is responsible for keeping their desk tidy.",
  "bring about":        "The new policy is expected to bring about positive change.",
  "carry out":          "Scientists carried out a series of experiments over six months.",
  "come across":        "I came across an interesting article about space travel.",
  "come up with":       "She came up with a brilliant idea during the meeting.",
  "deal with":          "Learning to deal with stress is an important life skill.",
  "due to":             "The game was canceled due to heavy rain.",
  "focus on":           "During exam season, try to focus on the most important topics.",
  "get rid of":         "It's time to get rid of old habits that are holding you back.",
  "give rise to":       "Industrialization gave rise to many new economic opportunities.",
  "go through":         "She went through a lot of challenges before achieving her dream.",
  "in addition":        "In addition, the report includes a section on future trends.",
  "in contrast":        "In contrast, the northern region has a much colder climate.",
  "in fact":            "In fact, regular exercise can improve your academic performance.",
  "in order to":        "She practiced every day in order to improve her English.",
  "in particular":      "Students, in particular those preparing for exams, found it helpful.",
  "in spite of":        "In spite of the rain, the outdoor event was a great success.",
  "in terms of":        "In terms of population, Tokyo is one of the world's largest cities.",
  "lead to":            "Poor diet and lack of exercise can lead to serious health issues.",
  "make use of":        "Make use of every opportunity to practice your English.",
  "on the other hand":  "Technology has many benefits; on the other hand, it can distract us.",
  "point out":          "The teacher pointed out several errors in the essay.",
  "regardless of":      "Everyone should be treated fairly regardless of their background.",
  "result in":          "The new teaching method resulted in higher student satisfaction.",
  "set up":             "They set up a new company specializing in renewable energy.",
  "take advantage of":  "Take advantage of every chance to speak English with native speakers.",
  "take part in":       "All students are encouraged to take part in the debate competition.",
  "take place":         "The ceremony will take place in the school hall on Friday.",
  "tend to":            "Students tend to perform better when they feel motivated.",
  "turn out":           "The trip turned out to be one of the best experiences of her life.",
  "with regard to":     "With regard to the proposal, we need more time to review it.",
  "according to":       "According to the report, global temperatures have risen by 1.2°C.",
  "aim at":             "The program aims at improving literacy among young children.",
  "be capable of":      "She is fully capable of handling the project independently.",
  "be familiar with":   "Are you familiar with the rules for the exam?",
  "be involved in":     "He was deeply involved in the planning of the event.",
  "be made up of":      "The committee is made up of teachers, parents, and students.",
  "contribute to":      "Everyone can contribute to making the world a better place.",
  "cope with":          "She found it difficult to cope with the pressure of exams.",
  "draw attention to":  "The campaign aims to draw attention to the issue of food waste.",
  "find out":           "I need to find out what time the event starts.",
  "give up":            "Don't give up, even when things seem difficult.",
  "look into":          "The company is looking into ways to reduce its energy use.",
  "make progress":      "With regular practice, you will definitely make progress.",
  "pay attention to":   "Pay attention to the details when proofreading your work.",
  "refer to":           "Please refer to the map on page 10 for directions.",
  "rely on":            "Many people rely on public transport to get to work.",
  "respond to":         "The government responded to the crisis with emergency funding.",
  "stand for":          "The letters 'UN' stand for United Nations.",
  "succeed in":         "With enough effort, you can succeed in achieving your goals.",
  "take care of":       "Please take care of yourself during the busy exam period.",
  "take into account":  "We must take into account the environmental impact of this plan.",
  "be subject to":      "All employees are subject to the company's code of conduct.",
  "in the long run":    "In the long run, regular study is more effective than cramming.",
  "on a regular basis": "Review your notes on a regular basis to retain information.",
  "as opposed to":      "She prefers studying alone, as opposed to working in groups.",
  "make a difference":  "Even small actions can make a difference to the environment.",
  "have access to":     "Students have access to the library's online database at home.",
  "in response to":     "The policy was introduced in response to public concern.",
  "at the expense of":  "Don't improve one area at the expense of another.",
  "make an effort":     "Make an effort to use new vocabulary in your daily writing.",
  "put into practice":  "It is one thing to learn a theory and another to put it into practice.",
  "as well as":         "She speaks English as well as French and Spanish.",
  "rather than":        "Rather than giving up, she worked even harder.",
  "in the short term":  "The plan may be costly in the short term but profitable in the future.",
  "on the basis of":    "The decision was made on the basis of the available evidence.",
  "be likely to":       "Students who review regularly are more likely to pass the exam.",
  "have an impact on":  "A good teacher can have a lasting impact on a student's life.",
  "be associated with": "Regular exercise is associated with better mental health.",
  "in addition to":     "In addition to studying, she volunteers at a local charity.",
};
