export const WORD_LIST = [
  // ── 動詞 ──────────────────────────────────────────
  ["abandon","捨てる、放棄する"],["accelerate","加速する"],["accomplish","達成する"],
  ["accuse","告発する、非難する"],["achieve","達成する"],["acquire","習得する、取得する"],
  ["adapt","適応する"],["adjust","調整する"],["adopt","採用する、養子にする"],
  ["advertise","宣伝する"],["affect","影響を与える"],["afford","〜する余裕がある"],
  ["analyze","分析する"],["announce","発表する"],["apply","応募する、適用する"],
  ["appreciate","感謝する、鑑賞する"],["approach","近づく、取り組む"],["approve","承認する"],
  ["argue","主張する、言い争う"],["arrange","手配する、整理する"],["assist","手伝う、支援する"],
  ["assume","仮定する、思い込む"],["attempt","試みる"],["attract","引き付ける"],
  ["avoid","避ける"],["blame","責める"],["calculate","計算する"],
  ["capture","捕まえる"],["cause","引き起こす"],["challenge","挑戦する"],
  ["claim","主張する"],["collaborate","協力する"],["communicate","伝える、連絡する"],
  ["compare","比較する"],["compete","競争する"],["complain","不満を言う"],
  ["complete","完成させる"],["concentrate","集中する"],["confirm","確認する"],
  ["connect","つなぐ"],["consider","考慮する"],["consume","消費する"],
  ["contribute","貢献する"],["convince","納得させる"],["cope","対処する"],
  ["create","創造する"],["criticize","批判する"],["damage","損傷を与える"],
  ["debate","議論する"],["decline","断る、減少する"],["decrease","減少する"],
  ["define","定義する"],["deliver","届ける"],["demand","要求する"],
  ["demonstrate","示す、実演する"],["depend","頼る"],["describe","説明する、描写する"],
  ["design","設計する"],["destroy","破壊する"],["develop","発展する、開発する"],
  ["direct","指示する"],["discover","発見する"],["discuss","話し合う"],
  ["distribute","配布する"],["divide","分ける"],["earn","稼ぐ"],
  ["educate","教育する"],["eliminate","排除する"],["emphasize","強調する"],
  ["encourage","励ます"],["ensure","確保する"],["establish","設立する"],
  ["estimate","推定する"],["evaluate","評価する"],["examine","調べる"],
  ["exhibit","展示する"],["expand","拡大する"],["explain","説明する"],
  ["export","輸出する"],["expose","さらす"],["express","表現する"],
  ["extend","延長する、拡張する"],["focus","集中する"],["force","強制する"],
  ["generate","生み出す"],["guarantee","保証する"],["handle","扱う"],
  ["harm","害を与える"],["identify","特定する"],["ignore","無視する"],
  ["illustrate","例示する、説明する"],["implement","実施する"],["import","輸入する"],
  ["improve","改善する"],["include","含む"],["increase","増加する"],
  ["indicate","示す"],["influence","影響を与える"],["inform","知らせる"],
  ["investigate","調査する"],["involve","含む、関与する"],["justify","正当化する"],
  ["launch","始める、発射する"],["limit","制限する"],["maintain","維持する"],
  ["manage","管理する、何とかする"],["manufacture","製造する"],["measure","測る"],
  ["modify","修正する"],["motivate","動機付ける"],["negotiate","交渉する"],
  ["obtain","得る"],["operate","操作する、運営する"],["oppose","反対する"],
  ["organize","整理する、組織する"],["overcome","克服する"],["participate","参加する"],
  ["perform","行う、演じる"],["permit","許可する"],["persuade","説得する"],
  ["predict","予測する"],["prepare","準備する"],["present","発表する、提示する"],
  ["prevent","防ぐ"],["produce","生産する"],["promote","促進する"],
  ["propose","提案する"],["protect","保護する"],["provide","提供する"],
  ["publish","出版する"],["purchase","購入する"],["realize","気づく、実現する"],
  ["recognize","認識する"],["reduce","減らす"],["refer","参照する"],
  ["reject","拒否する"],["replace","取り替える"],["represent","代表する"],
  ["require","必要とする"],["research","研究する"],["resolve","解決する"],
  ["respond","応答する"],["restrict","制限する"],["reveal","明らかにする"],
  ["solve","解決する"],["submit","提出する"],["suggest","提案する"],
  ["support","支持する"],["survive","生き残る"],["transfer","移す、転送する"],
  ["transform","変換する"],["treat","扱う、治療する"],["update","更新する"],
  ["vary","異なる、変化する"],["waste","無駄にする"],["withdraw","撤退する、引き出す"],
  ["abolish","廃止する"],["absorb","吸収する"],["accommodate","収容する、適応させる"],
  ["acknowledge","認める"],["activate","活性化する"],["adhere","固執する、付着する"],
  ["administer","管理する、投与する"],["advocate","主張する、支持する"],["allocate","割り当てる"],
  ["alter","変える"],["appeal","訴える"],["assess","評価する"],
  ["associate","関連付ける"],["authorize","権限を与える"],["categorize","分類する"],
  ["compile","まとめる、編集する"],["coordinate","調整する"],["customize","カスタマイズする"],
  ["dedicate","捧げる"],["delegate","委任する"],["derive","引き出す、由来する"],
  ["determine","決定する"],["devote","捧げる"],["differentiate","区別する"],
  ["diminish","減少する"],["document","記録する"],["dominate","支配する"],
  ["enable","可能にする"],["engage","従事する"],["enhance","高める"],
  ["exchange","交換する"],["facilitate","容易にする"],["gather","集める"],
  ["incorporate","組み込む"],["integrate","統合する"],["interpret","解釈する"],
  ["locate","位置を特定する"],["monitor","監視する"],["perceive","知覚する"],
  ["preserve","保存する"],["prioritize","優先する"],["pursue","追求する"],
  ["reinforce","強化する"],["release","解放する、発表する"],["rely","頼る"],
  ["select","選択する"],["separate","分離する"],["specify","明記する"],
  ["stabilize","安定させる"],["strengthen","強化する"],["track","追跡する"],
  ["utilize","活用する"],["validate","検証する"],["comprehend","理解する"],
  ["elaborate","詳しく説明する"],["fluctuate","変動する"],["formulate","策定する"],
  ["generalize","一般化する"],["initiate","開始する"],["neutralize","中和する"],
  ["optimize","最適化する"],["rationalize","合理化する"],["simplify","単純化する"],
  ["standardize","標準化する"],["symbolize","象徴する"],["undermine","損なう"],
  ["violate","違反する"],["withstand","耐える"],["aggregate","集める"],
  ["anticipate","予期する"],["clarify","明確にする"],["compensate","補償する"],
  ["comply","従う"],["conform","従う"],["contaminate","汚染する"],
  ["convert","変換する"],["degrade","低下させる"],["diagnose","診断する"],
  ["discriminate","差別する"],["enforce","施行する"],["exploit","利用する"],
  ["inspire","刺激する"],["mobilize","動員する"],["neglect","無視する"],
  ["observe","観察する"],["reconstruct","再建する"],["reinstate","復活させる"],
  ["renew","更新する"],["stimulate","刺激する"],["substitute","代替する"],
  ["sustain","維持する"],["underestimate","過小評価する"],["alleviate","緩和する"],
  ["amplify","拡大する"],["assert","主張する"],["confront","直面する"],
  ["impose","課す"],["induce","引き起こす"],["regulate","規制する"],
  ["revolutionize","革命的に変える"],["sacrifice","犠牲にする"],["upgrade","改良する"],

  // ── 名詞 ──────────────────────────────────────────
  ["ability","能力"],["absence","不在、欠如"],["access","アクセス"],
  ["accident","事故"],["achievement","達成"],["activity","活動"],
  ["advantage","利点"],["advice","アドバイス"],["agreement","合意"],
  ["aid","援助"],["aim","目標"],["alternative","代替案"],
  ["analysis","分析"],["announcement","発表"],["anxiety","不安"],
  ["area","分野、地域"],["argument","議論"],["aspect","側面"],
  ["assistance","支援"],["atmosphere","雰囲気、大気"],["attitude","態度"],
  ["authority","権威"],["awareness","認識"],["benefit","利益"],
  ["behavior","行動"],["career","職業、キャリア"],["circumstance","状況"],
  ["commitment","約束、献身"],["communication","コミュニケーション"],["competition","競争"],
  ["condition","状態"],["confidence","自信"],["conflict","対立"],
  ["consequence","結果"],["contribution","貢献"],["controversy","論争"],
  ["cooperation","協力"],["criticism","批判"],["culture","文化"],
  ["danger","危険"],["decision","決定"],["desire","欲望"],
  ["development","発展"],["difference","違い"],["difficulty","困難"],
  ["disadvantage","不利"],["discovery","発見"],["diversity","多様性"],
  ["economy","経済"],["education","教育"],["effect","効果"],
  ["efficiency","効率"],["effort","努力"],["element","要素"],
  ["emergency","緊急事態"],["emotion","感情"],["emphasis","強調"],
  ["environment","環境"],["equality","平等"],["error","誤り"],
  ["evidence","証拠"],["evolution","進化"],["expectation","期待"],
  ["experience","経験"],["explanation","説明"],["failure","失敗"],
  ["flexibility","柔軟性"],["freedom","自由"],["function","機能"],
  ["goal","目標"],["growth","成長"],["guideline","指針"],
  ["habit","習慣"],["health","健康"],["impact","影響"],
  ["improvement","改善"],["income","収入"],["independence","独立"],
  ["influence","影響"],["infrastructure","インフラ"],["issue","問題"],
  ["knowledge","知識"],["leadership","リーダーシップ"],["limitation","制限"],
  ["media","メディア"],["method","方法"],["motivation","動機"],
  ["movement","運動"],["necessity","必要性"],["objective","目標"],
  ["obstacle","障害"],["opportunity","機会"],["organization","組織"],
  ["outcome","結果"],["pattern","パターン"],["perception","認識"],
  ["performance","パフォーマンス"],["perspective","視点"],["phenomenon","現象"],
  ["policy","政策"],["population","人口"],["poverty","貧困"],
  ["preference","好み"],["pressure","圧力"],["priority","優先事項"],
  ["progress","進歩"],["property","財産"],["proposal","提案"],
  ["protection","保護"],["purpose","目的"],["quality","品質"],
  ["reality","現実"],["recognition","認識"],["relationship","関係"],
  ["reputation","評判"],["requirement","要件"],["resource","資源"],
  ["responsibility","責任"],["result","結果"],["safety","安全"],
  ["satisfaction","満足"],["shortage","不足"],["significance","重要性"],
  ["situation","状況"],["skill","技能"],["solution","解決策"],
  ["standard","基準"],["strategy","戦略"],["strength","強み"],
  ["struggle","闘い"],["success","成功"],["technology","技術"],
  ["tendency","傾向"],["trend","トレンド"],["variety","多様性"],
  ["weakness","弱点"],["welfare","福祉"],["acquisition","取得"],
  ["adaptation","適応"],["administration","管理"],["advocacy","支持"],
  ["allocation","割り当て"],["amendment","修正"],["appreciation","感謝"],
  ["assumption","仮定"],["authorization","承認"],["capability","能力"],
  ["category","カテゴリー"],["collaboration","協力"],["component","構成要素"],
  ["concept","概念"],["context","文脈"],["convention","慣習"],
  ["correlation","相関"],["currency","通貨"],["declaration","宣言"],
  ["delivery","配達"],["democracy","民主主義"],["dimension","次元"],
  ["discipline","規律"],["distribution","分配"],["domain","分野"],
  ["emission","排出"],["evaluation","評価"],["factor","要因"],
  ["feedback","フィードバック"],["finance","財政"],["framework","枠組み"],
  ["generation","世代"],["governance","統治"],["hypothesis","仮説"],
  ["identity","アイデンティティ"],["implementation","実施"],["integration","統合"],
  ["interpretation","解釈"],["intervention","介入"],["investment","投資"],
  ["labor","労働"],["legislation","法律"],["mechanism","メカニズム"],
  ["monitoring","監視"],["network","ネットワーク"],["optimization","最適化"],
  ["output","出力"],["participant","参加者"],["philosophy","哲学"],
  ["procedure","手順"],["profit","利益"],["project","プロジェクト"],
  ["provision","提供"],["ratio","比率"],["regulation","規制"],
  ["restriction","制限"],["revenue","収益"],["risk","リスク"],
  ["scenario","シナリオ"],["sector","分野"],["sequence","順序"],
  ["statistics","統計"],["structure","構造"],["sustainability","持続可能性"],
  ["transformation","変革"],["transition","移行"],["unemployment","失業"],
  ["variation","変動"],["workforce","労働力"],["accomplishment","業績"],
  ["adolescent","青少年"],["affluence","豊かさ"],["aftermath","余波"],
  ["agenda","議題"],["ambition","野心"],["apprehension","不安"],
  ["asset","資産"],["automation","自動化"],["autonomy","自律"],
  ["backlash","反発"],["benchmark","基準"],["bias","偏見"],
  ["breakdown","崩壊"],["bureaucracy","官僚制"],["capacity","容量、能力"],
  ["competence","能力"],["complication","複雑さ"],["consciousness","意識"],
  ["constraint","制約"],["corruption","腐敗"],["creativity","創造性"],
  ["credibility","信頼性"],["crisis","危機"],["criterion","基準"],
  ["curiosity","好奇心"],["dedication","献身"],["deficiency","不足"],
  ["demographic","人口統計"],["dependency","依存"],["deterioration","悪化"],
  ["dignity","尊厳"],["disruption","混乱"],["dominance","優位"],
  ["drawback","欠点"],["eligibility","資格"],["engagement","関与"],
  ["epidemic","流行病"],["exclusion","排除"],["exploitation","搾取"],
  ["exposure","露出"],["fluctuation","変動"],["gap","格差"],
  ["globalization","グローバル化"],["hierarchy","階層"],["hostility","敵意"],
  ["ideology","イデオロギー"],["imbalance","不均衡"],["inclusion","包摂"],
  ["inequality","不平等"],["initiative","主導権"],["innovation","革新"],
  ["insight","洞察"],["integrity","誠実さ"],["interaction","相互作用"],
  ["justification","正当化"],["liability","責任"],["mediation","調停"],
  ["minority","少数派"],["modernization","近代化"],["morale","士気"],
  ["negotiation","交渉"],["norm","規範"],["obligation","義務"],
  ["oppression","抑圧"],["penalty","罰則"],["polarization","二極化"],
  ["potential","可能性"],["privilege","特権"],["progression","進展"],
  ["prosperity","繁栄"],["rationality","合理性"],["reform","改革"],
  ["reliability","信頼性"],["resilience","回復力"],["resolution","解決"],
  ["rhetoric","修辞"],["solidarity","連帯"],["sovereignty","主権"],
  ["spectrum","スペクトル"],["stereotype","固定観念"],["stimulus","刺激"],
  ["subordinate","部下"],["superiority","優越"],["suppression","抑圧"],
  ["tolerance","寛容"],["transparency","透明性"],["trauma","トラウマ"],
  ["uncertainty","不確実性"],["unity","統一"],["validity","妥当性"],
  ["vulnerability","脆弱性"],["catalyst","触媒"],["momentum","勢い"],
  ["precedent","先例"],["repercussion","影響、余波"],["breakthrough","突破口"],
  ["milestone","節目"],["pitfall","落とし穴"],["endeavor","努力"],
  ["foundation","基盤"],["incentive","動機づけ"],["implication","含意"],
  ["misconception","誤解"],["contradiction","矛盾"],["revelation","暴露"],
  ["paradox","逆説"],["dilemma","ジレンマ"],["consensus","合意"],
  ["compromise","妥協"],["enthusiasm","熱意"],["compassion","思いやり"],
  ["prejudice","偏見"],

  // ── 形容詞 ────────────────────────────────────────
  ["abundant","豊富な"],["accurate","正確な"],["adequate","十分な"],
  ["appropriate","適切な"],["available","利用可能な"],["aware","気づいている"],
  ["capable","有能な"],["certain","確かな"],["comfortable","快適な"],
  ["complex","複雑な"],["confident","自信のある"],["considerable","かなりの"],
  ["consistent","一貫した"],["controversial","論争の的な"],["convenient","便利な"],
  ["creative","創造的な"],["critical","重要な、批判的な"],["decisive","決断力のある"],
  ["determined","決意した"],["diverse","多様な"],["effective","効果的な"],
  ["efficient","効率的な"],["essential","不可欠な"],["evident","明らかな"],
  ["excessive","過度の"],["flexible","柔軟な"],["fundamental","基本的な"],
  ["genuine","本物の"],["global","世界的な"],["gradual","徐々の"],
  ["harmful","有害な"],["immediate","即座の"],["independent","独立した"],
  ["inevitable","避けられない"],["influential","影響力のある"],["innovative","革新的な"],
  ["limited","限られた"],["logical","論理的な"],["loyal","忠実な"],
  ["mature","成熟した"],["meaningful","意味のある"],["moderate","適度な"],
  ["motivated","やる気のある"],["mutual","相互の"],["negative","否定的な"],
  ["neutral","中立的な"],["obvious","明らかな"],["ordinary","普通の"],
  ["original","独創的な"],["outstanding","優れた"],["passionate","情熱的な"],
  ["persistent","粘り強い"],["physical","身体的な"],["political","政治的な"],
  ["positive","前向きな"],["potential","潜在的な"],["practical","実用的な"],
  ["precise","正確な"],["productive","生産的な"],["professional","プロの"],
  ["prominent","著名な"],["reasonable","合理的な"],["relevant","関連した"],
  ["reliable","信頼できる"],["remarkable","注目すべき"],["responsible","責任感のある"],
  ["significant","重要な"],["specific","具体的な"],["stable","安定した"],
  ["suitable","適切な"],["sustainable","持続可能な"],["technical","技術的な"],
  ["temporary","一時的な"],["traditional","伝統的な"],["typical","典型的な"],
  ["unique","独自の"],["vital","不可欠な"],["voluntary","自発的な"],
  ["academic","学術的な"],["accessible","アクセスしやすい"],["active","積極的な"],
  ["adaptive","適応的な"],["affordable","手頃な"],["aggressive","積極的な"],
  ["analytical","分析的な"],["autonomous","自律的な"],["beneficial","有益な"],
  ["collective","集団的な"],["commercial","商業的な"],["compatible","互換性のある"],
  ["competitive","競争力のある"],["comprehensive","包括的な"],["continuous","継続的な"],
  ["cooperative","協力的な"],["corporate","企業の"],["cultural","文化的な"],
  ["democratic","民主的な"],["digital","デジタルの"],["diplomatic","外交的な"],
  ["dominant","支配的な"],["economic","経済的な"],["educational","教育的な"],
  ["environmental","環境の"],["ethical","倫理的な"],["extensive","広範な"],
  ["external","外部の"],["formal","正式な"],["functional","機能的な"],
  ["governmental","政府の"],["historical","歴史的な"],["identical","同一の"],
  ["industrial","産業の"],["intellectual","知的な"],["intensive","集中的な"],
  ["intermediate","中間の"],["internal","内部の"],["legislative","立法の"],
  ["marginal","わずかな"],["monetary","金融の"],["moral","道徳的な"],
  ["multinational","多国籍の"],["numerical","数値的な"],["organic","有機の"],
  ["popular","人気のある"],["rational","合理的な"],["regional","地域の"],
  ["regulatory","規制の"],["robust","頑丈な"],["secondary","二次的な"],
  ["sensitive","敏感な"],["sophisticated","洗練された"],["statistical","統計的な"],
  ["strategic","戦略的な"],["structural","構造的な"],["substantial","かなりの"],
  ["systematic","組織的な"],["transparent","透明な"],["universal","普遍的な"],
  ["urban","都市の"],["valuable","価値のある"],["diligent","勤勉な"],
  ["eloquent","雄弁な"],["ambiguous","曖昧な"],["concise","簡潔な"],
  ["vulnerable","脆弱な"],["optimistic","楽観的な"],["pessimistic","悲観的な"],
  ["indifferent","無関心な"],["reluctant","気乗りしない"],["skeptical","懐疑的な"],
  ["ambitious","野心的な"],["courageous","勇敢な"],["humble","謙虚な"],
  ["arrogant","傲慢な"],["tolerant","寛容な"],["stubborn","頑固な"],
  ["generous","寛大な"],["sympathetic","同情的な"],["passive","受動的な"],
  ["proactive","積極的な"],["objective","客観的な"],["subjective","主観的な"],
  ["abstract","抽象的な"],["concrete","具体的な"],["explicit","明示的な"],
  ["implicit","暗示的な"],["inherent","本質的な"],["arbitrary","恣意的な"],
  ["spontaneous","自発的な"],["deliberate","意図的な"],["domestic","国内の"],
  ["foreign","外国の"],["annual","年間の"],["contemporary","現代の"],
  ["conventional","従来の"],["notorious","悪名高い"],["legitimate","正当な"],
  ["feasible","実行可能な"],["plausible","もっともらしい"],["credible","信頼できる"],
  ["coherent","一貫した"],["urgent","緊急の"],["enormous","巨大な"],
  ["profound","深い"],["subtle","微妙な"],["valid","有効な"],

  // ── 副詞 ──────────────────────────────────────────
  ["absolutely","絶対に"],["additionally","さらに"],["apparently","どうやら"],
  ["approximately","おおよそ"],["certainly","確かに"],["clearly","明らかに"],
  ["commonly","一般的に"],["completely","完全に"],["consistently","一貫して"],
  ["continuously","継続的に"],["currently","現在"],["definitely","確かに"],
  ["effectively","効果的に"],["especially","特に"],["essentially","本質的に"],
  ["eventually","最終的に"],["exactly","正確に"],["frequently","頻繁に"],
  ["generally","一般的に"],["gradually","徐々に"],["highly","非常に"],
  ["increasingly","ますます"],["individually","個別に"],["initially","最初に"],
  ["largely","主に"],["mainly","主に"],["moreover","さらに"],
  ["nearly","ほとんど"],["obviously","明らかに"],["particularly","特に"],
  ["perfectly","完全に"],["practically","実際には"],["precisely","正確に"],
  ["primarily","主に"],["probably","おそらく"],["properly","適切に"],
  ["rapidly","急速に"],["rarely","めったに〜ない"],["reasonably","合理的に"],
  ["recently","最近"],["regularly","定期的に"],["relatively","比較的"],
  ["repeatedly","繰り返し"],["significantly","大幅に"],["simply","単純に"],
  ["specifically","具体的に"],["slightly","わずかに"],["strongly","強く"],
  ["suddenly","突然"],["temporarily","一時的に"],["typically","典型的に"],
  ["ultimately","最終的に"],["usually","通常"],["virtually","事実上"],
  ["widely","広く"],["accordingly","したがって"],["alternatively","あるいは"],
  ["consequently","結果として"],["deliberately","意図的に"],["dramatically","劇的に"],
  ["extensively","広範に"],["fundamentally","根本的に"],["literally","文字通り"],
  ["logically","論理的に"],["naturally","自然に"],["necessarily","必ずしも"],
  ["notably","特に"],["previously","以前に"],["radically","根本的に"],
  ["remarkably","著しく"],["technically","技術的に"],["traditionally","伝統的に"],

  // ── 熟語・イディオム ──────────────────────────────
  ["account for","〜を説明する、占める"],["adapt to","〜に適応する"],
  ["apply for","〜に申し込む"],["as a result","その結果"],
  ["at the same time","同時に"],["be aware of","〜を知っている"],
  ["be based on","〜に基づいている"],["be concerned about","〜を心配する"],
  ["be responsible for","〜に責任がある"],["bring about","〜をもたらす"],
  ["carry out","〜を実行する"],["come across","偶然見つける"],
  ["come up with","〜を思いつく"],["deal with","〜に対処する"],
  ["due to","〜のために"],["focus on","〜に集中する"],
  ["get rid of","〜を取り除く"],["give rise to","〜を引き起こす"],
  ["go through","〜を経験する"],["in addition","さらに"],
  ["in contrast","対照的に"],["in fact","実際には"],
  ["in order to","〜するために"],["in particular","特に"],
  ["in spite of","〜にもかかわらず"],["in terms of","〜の観点から"],
  ["lead to","〜につながる"],["make use of","〜を活用する"],
  ["on the other hand","一方"],["point out","指摘する"],
  ["regardless of","〜にかかわらず"],["result in","〜という結果になる"],
  ["set up","〜を設立する"],["take advantage of","〜を利用する"],
  ["take part in","〜に参加する"],["take place","起こる"],
  ["tend to","〜する傾向がある"],["turn out","〜であることがわかる"],
  ["with regard to","〜に関して"],["according to","〜によると"],
  ["aim at","〜を目指す"],["be capable of","〜できる"],
  ["be familiar with","〜に精通している"],["be involved in","〜に関わっている"],
  ["be made up of","〜で構成されている"],["contribute to","〜に貢献する"],
  ["cope with","〜に対処する"],["draw attention to","〜に注目を集める"],
  ["find out","〜を調べる、発見する"],["give up","あきらめる"],
  ["look into","〜を調査する"],["make progress","進歩する"],
  ["pay attention to","〜に注意を払う"],["refer to","〜を参照する"],
  ["rely on","〜に頼る"],["respond to","〜に応答する"],
  ["stand for","〜を表す"],["succeed in","〜に成功する"],
  ["take care of","〜の世話をする"],["take into account","〜を考慮する"],
  ["be subject to","〜に従う、〜を受ける"],["in the long run","長期的には"],
  ["on a regular basis","定期的に"],["as opposed to","〜とは対照的に"],
  ["make a difference","違いを生む"],["have access to","〜にアクセスできる"],
  ["in response to","〜に対応して"],["at the expense of","〜を犠牲にして"],
  ["make an effort","努力する"],["put into practice","実践する"],
  ["as well as","〜だけでなく"],["rather than","〜よりむしろ"],
  ["in the short term","短期的には"],["on the basis of","〜に基づいて"],
  ["be likely to","〜しそうである"],["have an impact on","〜に影響を与える"],
  ["be associated with","〜と関連している"],["in addition to","〜に加えて"],
];
